### ISSUE TITLE
query conditions with _id should not be modified

### ISSUE THREAD

**Issue by weisjohn** [weisjohn/mongoose-deleted#4]
Mongoose's `.populate()` feature simple does a query with `this._conditions` like:

``` javascript
{ _id: { '$in': [ 53c7d351b97f91f7564c3ce9 ] } }
```

In this case, we probably should not add `deleted: false`. Otherwise, we almost destroy the benefit of `.populate()`.

**Comment by michaek** [comment]
Does this change mean that if you find a record by `_id` you'll receive it even if it has `deleted: true`?

**Comment by weisjohn** [comment]
@michaek yes. My reasoning at the time is this: if you know the _id itself, you probably are either doing a findByOne or there's a reference to it somewhere else in your schema. If a document in Model A references a deleted item in Model B, `mongoose-deleted` can't really do anything about that; i.e. there's no notion of cascading deletes. So I figured I'd open it up. 

If you really need it to not to that, I think I could expose a feature to toggle this functionality. 

Thoughts?
